# Generated by Django 3.2.3 on 2023-03-20 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cntag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='cntaggeditem',
            options={'verbose_name': 'tag_item', 'verbose_name_plural': 'tag_items'},
        ),
        migrations.AlterField(
            model_name='cntaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='photoapp.cntag'),
        ),
    ]
